name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the destroy job

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.4.0
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          terraform init
        working-directory: ./terraform

      - name: Terraform Format
        run: |
          terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Validate
        run: |
          terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        working-directory: ./terraform
        continue-on-error: false  # Ensures that any failure in this step stops the workflow

      - name: Output Terraform Plan
        run: |
          terraform show
        working-directory: ./terraform

  destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Runs only on manual triggers

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.4.0
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
        working-directory: ./terraform
